import { RolePermissionConstant } from './Roles.types';

export const ROLE_PERMISSIONS: RolePermissionConstant[] = [
  {
    text: 'Dashboard',
    section_title: true,
  },
  {
    text: 'View dashboards',
    viewer: true,
    contributor: true,
    admin: true,
    owner: true,
  },
  {
    text: 'Data sources',
    section_title: true,
  },
  {
    text: 'View data sources',
    viewer: true,
    contributor: true,
    admin: true,
    owner: true,
  },
  {
    text: 'Create, edit, and delete data sources',
    viewer: false,
    contributor: false,
    admin: true,
    owner: true,
  },
  {
    text: 'Policies',
    section_title: true,
  },
  {
    text: 'View policies details',
    viewer: true,
    contributor: true,
    admin: true,
    owner: true,
  },
  {
    text: 'Create, edit, and delete policies',
    viewer: false,
    contributor: true,
    admin: true,
    owner: true,
  },
  {
    text: 'Manage policy coverage',
    viewer: false,
    contributor: true,
    admin: true,
    owner: true,
  },
  {
    text: 'View, create, edit, and delete policy exceptions',
    viewer: false,
    contributor: true,
    admin: true,
    owner: true,
  },
  {
    text: 'View, create, edit, and delete policy categories',
    viewer: false,
    contributor: false,
    admin: true,
    owner: true,
  },
  {
    text: 'Enable/disable policy frameworks',
    viewer: false,
    contributor: false,
    admin: true,
    owner: true,
  },
  {
    text: 'Violations',
    section_title: true,
  },
  {
    text: 'View violations',
    viewer: true,
    contributor: true,
    admin: true,
    owner: true,
  },
  {
    text: 'Mark violations as exceptions',
    viewer: false,
    contributor: true,
    admin: true,
    owner: true,
  },
  {
    text: 'Workflows',
    section_title: true,
  },
  {
    text: 'View workflows',
    viewer: true,
    contributor: true,
    admin: true,
    owner: true,
  },
  {
    text: 'View, create, edit, and delete workflows',
    viewer: false,
    contributor: false,
    admin: true,
    owner: true,
  },
  {
    text: 'Integrations',
    section_title: true,
  },
  {
    text: 'View integrations',
    viewer: true,
    contributor: true,
    admin: true,
    owner: true,
  },
  {
    text: 'View, create, edit, and delete integrations',
    viewer: false,
    contributor: false,
    admin: true,
    owner: true,
  },
  {
    text: 'Reports',
    section_title: true,
  },
  {
    text: 'View reports',
    viewer: true,
    contributor: true,
    admin: true,
    owner: true,
  },
  {
    text: 'Create, edit, and delete reports',
    viewer: false,
    contributor: false,
    admin: true,
    owner: true,
  },
  {
    text: 'Activity log',
    section_title: true,
  },
  {
    text: 'View activity log',
    viewer: true,
    contributor: true,
    admin: true,
    owner: true,
  },
  {
    text: 'Organization & User management',
    section_title: true,
  },
  {
    text: 'View, create, edit, and delete organizations',
    viewer: false,
    contributor: false,
    admin: false,
    owner: true,
  },
  {
    text: 'Create, edit, and delete users',
    viewer: false,
    contributor: false,
    admin: false,
    owner: true,
  },
  {
    text: 'Manage user access',
    viewer: false,
    contributor: false,
    admin: true,
    owner: true,
  },
  {
    text: 'Enable SSO',
    viewer: false,
    contributor: false,
    admin: false,
    owner: true,
  },
];
